### ISSUE TITLE
The user's home directory is not your playground.

### ISSUE THREAD

**Issue by nc7s** [teambit/bvm#62]
A common practice is putting binaries into `~/.local/bin`. Or at least put it into your already own and dot hidden `~/.bvm`. The user's home directory belongs to, as the words imply, the user, not you.

https://github.com/teambit/bvm/issues/27 on the same matter received no response from the developers for SEVEN MONTHS. This is pure arrogance.

**Comment by GiladShoham** [comment]
This is a left overs since the days we haven't implemented the path update automatically.
so we put it there to reduce the friction of adding a step to manually update the path.
now that we already implemented it, we can replace the bin location.

**Comment by iham** [comment]
this is still an issue.
installing bvm and bit in a node container is frustrating and confusing:

on the one hand I have to install bvm as root in order to make it global. why?
on the other hand, after installing bit using bvm as root, the cli tells me to better not run bit as privileged user. what?! why?!

I want to be able to define how and where to install both.
inside a container it makes sense to run it as root or as node use - either way is fine.

how to tell bvm to install local?
how to tell bvm to install bit to a certain user?
how to change the bin directory? like from $HOME/bin (-> what the ...) to something common? (like /usr/local/bin or as mentioned inside $HOME/.bvm/bin

please elaborate and update docs on that.
thanks
